/*
Package c GENERATED BY gengo:defaulter
DON'T EDIT THIS FILE
*/
package c

func (v *C) SetDefault() {
	// TODO
}
func (v *DigestMeta) SetDefault() {
	// TODO
}
func (v *FileSize) SetDefault() {
	// TODO
}
func (v *KubePkg) SetDefault() {
	// TODO
}
func (v *KubePkgSpec) SetDefault() {
	// TODO
}
func (v *KubePkgStatus) SetDefault() {
	// TODO
}
func (v *Manifests) SetDefault() {
	// TODO
}
func (v *Statuses) SetDefault() {
	// TODO
}
