// Code generated by gengo:defaulter DO NOT EDIT.
package c

func (v *C) SetDefault() {
	// TODO
}

func (v *DigestMeta) SetDefault() {
	// TODO
}

func (v *FileSize) SetDefault() {
	// TODO
}

func (v *KubePkg) SetDefault() {
	// TODO
}

func (v *KubePkgSpec) SetDefault() {
	// TODO
}

func (v *KubePkgStatus) SetDefault() {
	// TODO
}

