// Code generated by gengo:defaulter DO NOT EDIT.
package b

func (v *B) SetDefault() {
	// TODO
}

func (v *List[T]) SetDefault() {
	// TODO
}

func (v *Obj) SetDefault() {
	// TODO
}

func (v *SubObj) SetDefault() {
	// TODO
}

func (v *Third) SetDefault() {
	// TODO
}
