/*
Package b GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package b

func (B) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{
		"B is a type for testing",
	}, true
}
func (v Obj) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{
				"name",
				"姓名",
			}, true
		case "SubObj":
			return []string{}, true

		}
		if doc, ok := v.SubObj.RuntimeDoc(names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (v SubObj) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Age":
			return []string{
				"Age",
			}, true

		}

		return nil, false
	}
	return []string{}, true
}
