/*
Package b GENERATED BY gengo:defaulter
DON'T EDIT THIS FILE
*/
package b

func (v *B) SetDefault() {
	// TODO
}
func (v *Obj) SetDefault() {
	// TODO
}
func (v *SubObj) SetDefault() {
	// TODO
}
func (v *Third) SetDefault() {
	// TODO
}
