package gengo

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/octohelm/x/cmp"
	. "github.com/octohelm/x/testing/v2"

	"github.com/octohelm/gengo/pkg/gengo/snippet"
)

func TestGenfileAPI(t *testing.T) {
	t.Run("Filename", func(t *testing.T) {
		gf := newGenfile("deepcopy")

		Then(t, "应按 baseName.name.go 规则生成文件名",
			Expect(gf.Filename(&GeneratorArgs{OutputFileBaseName: "zz_generated"}), Equal("zz_generated.deepcopy.go")),
		)
	})

	t.Run("writeImports", func(t *testing.T) {
		buf := bytes.NewBuffer(nil)
		writeImports(buf, map[string]string{
			"time":                       "time",
			"github.com/octohelm/x/cmp":  "cmp",
			"github.com/octohelm/x/slog": "slog",
		})

		out := buf.String()
		Then(t, "应输出 import 块",
			Expect(strings.Contains(out, "import ("), Be(cmp.True())),
		)
		Then(t, "应按路径字典序输出导入",
			Expect(strings.Index(out, `"github.com/octohelm/x/cmp"`) < strings.Index(out, `"github.com/octohelm/x/slog"`), Be(cmp.True())),
			Expect(strings.Index(out, `"github.com/octohelm/x/slog"`) < strings.Index(out, `"time"`), Be(cmp.True())),
		)
	})

	t.Run("WriteToFile", func(t *testing.T) {
		c := mustCtxOnPackage(t, "github.com/octohelm/gengo/pkg/gengo/testdata/runtime/c")
		gf := newGenfile("write_to_file")
		Must(t, func() error {
			return gf.InitWith(c)
		})

		args := &GeneratorArgs{
			OutputFileBaseName: "zz_generated_api_test",
		}
		filename := filepath.Join(c.Package("").SourceDir(), gf.Filename(args))
		t.Cleanup(func() {
			_ = os.Remove(filename)
		})

		t.Run("空内容应直接返回", func(t *testing.T) {
			Must(t, func() error {
				return gf.WriteToFile(c, args)
			})
			Then(t, "空内容不应落盘",
				ExpectMust(func() error {
					_, err := os.Stat(filename)
					if err == nil {
						return os.ErrExist
					}
					if os.IsNotExist(err) {
						return nil
					}
					return err
				}),
			)
		})

		t.Run("有渲染内容应写入文件", func(t *testing.T) {
			gf.Render(snippet.Block("const Answer = 42\n"))

			Must(t, func() error {
				return gf.WriteToFile(c, args)
			})

			data := MustValue(t, func() ([]byte, error) {
				return os.ReadFile(filename)
			})

			content := string(data)

			Then(t, "应包含生成头注释和 package 声明",
				Expect(strings.Contains(content, "Code generated by gengo:write_to_file DO NOT EDIT."), Be(cmp.True())),
				Expect(strings.Contains(content, "package c"), Be(cmp.True())),
			)
			Then(t, "应包含渲染的常量定义",
				Expect(strings.Contains(content, "const Answer = 42"), Be(cmp.True())),
			)
		})
	})
}

func TestPkgExecuteCachedAndCleanup(t *testing.T) {
	c := mustCtxOnPackage(t, "github.com/octohelm/gengo/pkg/gengo/testdata/runtime/c")
	pkgPath := c.pkg.Pkg().Path()

	t.Run("pkgChanged false 时应命中 cached 分支", func(t *testing.T) {
		c.args.Force = false
		c.sumFile = c.universe.SumFile()

		Must(t, func() error {
			return c.pkgExecute(context.Background(), pkgPath)
		})
	})

	t.Run("应删除遗留生成文件", func(t *testing.T) {
		staleFilename := filepath.Join(c.pkg.SourceDir(), "zz_generated_api_test_cleanup.stale.go")
		Must(t, func() error {
			return os.WriteFile(staleFilename, []byte("package c\n"), 0o644)
		})
		t.Cleanup(func() {
			_ = os.Remove(staleFilename)
		})

		executor := MustValue(t, func() (Executor, error) {
			return NewExecutor(&GeneratorArgs{
				Entrypoint:         []string{"github.com/octohelm/gengo/pkg/gengo/testdata/runtime/c"},
				OutputFileBaseName: "zz_generated_api_test_cleanup",
				Force:              true,
			})
		})
		cc := executor.(*gengoCtx)
		cc.pkg = cc.universe.Package(pkgPath)
		cc.l = newLogger()

		Must(t, func() error {
			return cc.pkgExecute(context.Background(), pkgPath, &namedOnlyGenerator{name: "not-enabled"})
		})

		Then(t, "执行后应清理遗留生成文件",
			ExpectMust(func() error {
				_, err := os.Stat(staleFilename)
				if os.IsNotExist(err) {
					return nil
				}
				if err != nil {
					return err
				}
				return os.ErrExist
			}),
		)
	})
}
