name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: extractions/setup-just@v3
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24'

      - run: just test-race